apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: node-metric-collector
    name: metrics-pvc